chatbotapp/chat/urls.py
from django.urls import path, re_path

from chat import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
]

chatbotapp/chatapp/urls.py
from django.urls import path

from chatapp import views

app_name = 'chatapp'

urlpatterns = [
    path('bot/', views.bot, name='bot'),
    path('result/', views.result, name='result'),
]

chatbotapp/chatbotapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('chat/', include('chat.urls')),
    path('chatapp/', include('chatapp.urls')),
    path('admin/', admin.site.urls),
]

chatbotapp/chat/models.py
from django.db import models

# Create your models here.

chatbotapp/chatapp/models.py
from django.db import models

# Create your models here.


class Profile(models.Model):
    name = models.CharField(max_length=200)


class Question(models.Model):
    text = models.CharField(max_length=200)


class Answer(models.Model):
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    profile = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)

chatbotapp/chat/views.py
import json

from django.shortcuts import render
from django.utils.safestring import mark_safe


def index(request):
    return render(request, 'chat/index.html', {})


def room(request, room_name):
    return render(request, 'chat/room.html', {
        'room_name_json': mark_safe(json.dumps(room_name))
    })

chatbotapp/chatapp/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render

from chatapp.models import Profile, Answer, Question


def bot(request):
    args = {}
    if request.method == 'POST' and request.is_ajax():
        if request.POST.get('question') == '1':
            user = Profile.objects.create(name=request.POST.get('answer'))
            next_question_id = int(request.POST.get('question')) + 1
            next_question = Question.objects.get(id=next_question_id)
            args['next_question_id'] = next_question.id
            args['next_question_text'] = next_question.text
            args['user'] = user.id

        else:
            Answer.objects.create(profile_id=int(request.POST.get('user')),
                                text=request.POST.get('answer'),
                                question_id=int(request.POST.get('question'))
                                )
            next_question_id = int(request.POST.get('question')) + 1
            if request.POST.get('question') == '3':
                args['button'] = 'true'
            try:
                next_question = Question.objects.get(id=next_question_id)
                args['next_question_id'] = next_question.id
                args['next_question_text'] = next_question.text
            except:
                args['end'] = 'end'
            args['user'] = request.POST.get('user')
        return HttpResponse(json.dumps(args), content_type='application/javascript; charset=utf8')
    else:
        question = Question.objects.first()
        args['question'] = question
        args['next'] = int(question.id) + 1
        return render(request, 'chatapp/bot.html', args)


def result(request):
    args = {}
    profile = Profile.objects.get(id=int(request.GET.get('user')))
    answers = Answer.objects.filter(profile_id=int(request.GET.get('user')))

    answers_text = answers[2].text
    if (answers_text == 'no'):
        smoker = 'non-smoker'
    else:
        smoker = 'smoker'

    args['answers'] = answers
    args['name'] = profile.name
    args['smoker'] = smoker

    return render(request, 'chatapp/result.html', args)

chatbotapp/chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

chatbotapp/chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"></head>
    <style>
        form {
            padding: 25px 100px;
            }
            @media only screen and (max-width: 600px) {
            form {  padding: 25px 10px; }
        }
    </style>
</head>
<body>

    <!--<input id="chat-message-input" type="text" size="100"/><br/>-->
    <!--<input id="chat-message-submit" type="button" value="Send" class="btn btn-success fa fa-paper-plane"/>-->

    <div class="row justify-content-center mt-2">
        <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
    </div>
    <div class="row justify-content-center mt-2">
        <form id="form1" style="box-shadow: 0px 0px 7px #8c8c8c;" class="col-12 col-md-6 mt-5 mb-5">
            <div class="row justify-content-center">
                <div class="col-auto">
                    <h5 id="question" style="margin-bottom:20px;color:#a6a6a6" class=""> {{question.text}}</h5>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-10">
                    <input required type="text" class="form-control" id="chat-message-input" question="{{question.id}}" placeholder="">
                </div>
                <div style="padding-left:0px;" class="col-auto">
                    <button id="chat-message-submit" type="button" onclick="myFunction()" class="btn btn-success fa fa-paper-plane"></button>
                </div>

            </div>
        </form>

    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
<script>
    var roomName = {{ room_name_json }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        document.querySelector('#chat-log').value += (message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = '';
    };
</script>
</html>

chatbotapp/chatapp/templates/chatapp/bot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chat Bot</title>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"></head>
    <style>
        form {
        padding: 25px 100px;
        }
        @media only screen and (max-width: 600px) {
        form {  padding: 25px 10px; }
}
    </style>
<body>
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-12 col-lg-8">
            <h2 style="text-align:center;font-weight:bold">Bot here ...</h2>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10">
            <h5 style="text-align:center">Hello, I am going to ask you few questions that will help me know you better
            </h5>
        </div>
    </div>
    <!--<div class="row justify-content-center mt-2">-->
        <!--<textarea id="chat-log" cols="40" rows="20"></textarea><br/>-->
    <!--</div>-->
    <div class="row justify-content-center mt-2">
        <div id="unique" style="margin-bottom:20px;color:#a6a6a6" class="col-md-12">
            <h5 style="float:right"> {{question.text}}</h5><br />
        </div>
    </div>
    <span style="display:none" id="csrf"> {{ csrf_token }}</span>
    <div class="row justify-content-center mt-2">
        <form id="form1" style="box-shadow: 0px 0px 7px #8c8c8c;" class="col-12 col-md-6 mt-5 mb-5">
            <div class="row justify-content-center">
                <!--<div class="col-auto">-->
                    <!--<h5 id="question" style="margin-bottom:20px;color:#a6a6a6" class=""> {{question.text}}</h5>-->
                <!--</div>-->
            </div>
            <div class="row justify-content-center">
                <div class="col-10">
                    <input required type="text" class="form-control" id="answer" question="{{question.id}}" placeholder="">
                </div>
                <div style="padding-left:0px;" class="col-auto">
                    <button id="sendbutton" type="button" onclick="myFunction()" class="btn btn-success fa fa-paper-plane"></button>
                </div>

            </div>
        </form>

    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script>
$(document).ready(function() {
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
});

function myFunction() {
    var formData = new FormData();
    formData.append('question', $('#answer').attr('question'));
    formData.append('answer', $('#answer').val());
    if ($('#answer').attr('user') != '') {
        formData.append('user', $('#answer').attr('user'));
    }

    $.ajax({
        url:"{% url 'chatapp:bot' %}",
        type: 'POST',
        headers: {'X-CSRFToken': $('#csrf').text()  },
        data: formData,
        async: false,
        success: function (data) {
            if ($('#answer').attr('question') == '4') {
                yo=window.location.protocol+ "//" + window.location.hostname+":"+window.location.port+"/chatapp/result/?user="+$('#answer').attr('user')
                window.location = yo
            }
            var data = jQuery.parseJSON(data);
            <!--$('#question').html(data.next_question_text)-->
            $('#unique').append("<h5 style=\"float:left\">" + $('#answer').val() + "</h5>" + "<br />");
            $('#unique').append("<h5 style=\"float:right\">" + data.next_question_text + "</h5>" + "<br />");
            $('#answer').val('')
            $('#answer').attr('question', data.next_question_id)
            $('#answer').attr('user', data.user)

            if (data.button == 'true') {
                $('#sendbutton').html('DONE')
                $('#sendbutton').removeClass('fa fa-paper-plane')
            }
        },
        error: function (data) {

        },
        cache: false,
        contentType: false,
        processData: false
   });
}

</script>
</body>
</html>

chatbotapp/chatapp/templates/chatapp/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chat Bot</title>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"></head>
    <style>
        form {
        padding: 25px 100px;
        }
        @media only screen and (max-width: 600px) {
        form {  padding: 25px 10px; }
}
    </style>
<body>
<div class="container">
    <span style="display:none" id="csrf"> {{ csrf_token }}</span>
    <div class="row justify-content-center mt-5">
        <div class="col-12 col-lg-8">
            <h2 style="text-align:center;font-weight:bold">Bot here ...</h2>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10">
            <h5 style="text-align:center">Here is overview of our chat:
            </h5>
        </div>
    </div>
    <div class="row justify-content-center mt-2">
        <form style="box-shadow: 0px 0px 7px #8c8c8c;" class="col-12 col-md-12 mt-5 mb-5">
            <div class="row justify-content-center">
                <div class="col-auto">
                    <h5 style="color:#a6a6a6" class="">
                        <b>{{name}}</b> was born in <b>{{answers.1.text}}</b> and is a <b>{{answers.0.text}}</b>  <b>{{smoker}}</b>
                    </h5>
                </div>
            </div>
        </form>

    </div>
</div>
</body>
</html>